INSERT INTO products (id, code, name, description, image,
                      category, price, quantity, internal_reference, shell_id,
                      inventory_status, rating, created_at, updated_at)
VALUES (1,
        'product-1',
        'Gaming Laptop',
        'High-performance gaming laptop with RTX 3080',
        'https://picsum.photos/id/1/300/200',
        'electronics',
        1999.99,
        10,
        'LAP-001',
        1,
        'INSTOCK',
        4.5,
        1708637416000,
        1708637416000);

INSERT INTO products (id, code, name, description, image,
                      category, price, quantity, internal_reference, shell_id,
                      inventory_status, rating, created_at, updated_at)
VALUES (2,
        'product-2',
        'Wireless Headphones',
        'Noise-cancelling Bluetooth headphones',
        'https://picsum.photos/id/2/300/200',
        'accessories',
        299.99,
        3,
        'HEAD-002',
        2,
        'LOWSTOCK',
        4.8,
        1708637416000,
        1708637416000);

INSERT INTO products (id, code, name, description, image,
                      category, price, quantity, internal_reference, shell_id,
                      inventory_status, rating, created_at, updated_at)
VALUES (3,
        'product-3',
        '4K Monitor',
        '32-inch 4K Ultra HD Monitor',
        'https://picsum.photos/id/3/300/200',
        'electronics',
        599.99,
        0,
        'MON-003',
        3,
        'OUTOFSTOCK',
        4.6,
        1708637416000,
        1708637416000);
